<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_car">
<xacro:include filename="$(find my_nav2_pkg)/urdf/lidar.xacro"/>

<gazebo>
  <plugin name="gazebo_ros_p3d" filename="libgazebo_ros_p3d.so">
    <ros>
      <namespace>/</namespace>
      <remapping>odom:=/odom</remapping>
    </ros>
    <body_name>base_link</body_name>
    <frame_name>odom</frame_name>
    <update_rate>50</update_rate>
    <gaussian_noise>0.01</gaussian_noise>
  </plugin>
</gazebo>



  <!-- ============ Properties ============ -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_length" value="0.05"/>
  <xacro:property name="wheel_mass" value="1.0"/>
  <xacro:property name="body_size_x" value="1.0"/>
  <xacro:property name="body_size_y" value="0.5"/>
  <xacro:property name="body_size_z" value="0.2"/>
  <xacro:property name="body_half_z" value="${body_size_z/2}"/> 
  <xacro:property name="wheel_y_offset" value="${body_size_y/2 + wheel_length/2}"/>
  <xacro:lidar parent_link="base_link"/>

  <!-- ============ Materials ============ -->
  <material name="blue"><color rgba="0 0 1 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>

  <!-- ============ Base Link ============ -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_size_x} ${body_size_y} ${body_size_z}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + body_half_z}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_size_x} ${body_size_y} ${body_size_z}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + body_half_z}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- ============ Steering Wheel Macro (front) ============ -->
  <xacro:macro name="steered_wheel" params="side x y">
    <link name="${side}_steering_link">
      <visual>
        <geometry><box size="0.01 0.01 0.01"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry><box size="0.01 0.01 0.01"/></geometry>
      </collision>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="1e-6" iyy="1e-6" izz="1e-6" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${side}_steering_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${side}_steering_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.5" upper="0.5" effort="100" velocity="1.0"/>
    </joint>

    <link name="${side}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
        <surface>
          <friction>
            <ode>
              <mu>1.0</mu>
              <mu2>1.0</mu2>
            </ode>
          </friction>
          <contact>
            <ode>
              <kp>1e5</kp>
              <kd>1.0</kd>
            </ode>
          </contact>
        </surface>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${side}_wheel_joint" type="continuous">
      <parent link="${side}_steering_link"/>
      <child link="${side}_wheel"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- FIXED Spin axis -->
    </joint>
  </xacro:macro>

  <!-- ============ Fixed Wheel Macro (rear) ============ -->
  <xacro:macro name="rear_wheel" params="side x y">
    <link name="${side}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
        <surface>
          <friction>
            <ode>
              <mu>1.0</mu>
              <mu2>1.0</mu2>
            </ode>
          </friction>
          <contact>
            <ode>
              <kp>1e5</kp>
              <kd>1.0</kd>
            </ode>
          </contact>
        </surface>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${side}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${side}_wheel"/>
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- FIXED Spin axis -->
    </joint>
  </xacro:macro>

  <!-- ============ Instantiate Wheels ============ -->
  <xacro:steered_wheel side="front_left"  x="0.5"  y="${wheel_y_offset}"/>
  <xacro:steered_wheel side="front_right" x="0.5"  y="-${wheel_y_offset}"/>
  <xacro:rear_wheel   side="rear_left"   x="-0.5" y="${wheel_y_offset}"/>
  <xacro:rear_wheel   side="rear_right"  x="-0.5" y="-${wheel_y_offset}"/>

  <!-- ============ ros2_control ============ -->
  <ros2_control name="my_car_control" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <!-- Steering joints -->
<!-- Steering joints (position control) -->
    <joint name="front_left_steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="front_right_steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>

<!-- Front wheel joints (passive, no command interface) -->
    <joint name="front_left_wheel_joint">
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_wheel_joint">
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

<!-- Rear wheel joints (driven by velocity control) -->
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
</ros2_control>

  <!-- ============ Gazebo plugins ============ -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <parameters>/home/surendra/ros2_ws/install/my_nav2_pkg/share/my_nav2_pkg/config/car_controllers.yaml</parameters>
    </plugin>
  </gazebo>

</robot>
